repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python]
  - repo: local
    hooks:
      - id: update-toc
        name: update toc
        entry: python -m scripts.update_toc
        language: system
        files: ^docs/
        pass_filenames: false
